/**
 * 通知ダミーデータ
 *
 * @概要
 *   - like/comment/admin種別をバランスよく含む20件のダミー通知データ。
 *   - 各通知はNotification型に準拠。
 */
import type { Notification } from "../../../types";

export const dummyNotifications: Notification[] = [
  {
    id: "notification-1",
    userId: "user-2",
    type: "like",
    entityId: "post-1",
    message: "山田太郎さんの投稿がいいねされました。",
    isRead: false,
    createdAt: "2024-05-01T10:30:00Z",
  },
  {
    id: "notification-2",
    userId: "user-3",
    type: "comment",
    entityId: "post-2",
    message: "佐藤花子さんの投稿にコメントが付きました。",
    isRead: false,
    createdAt: "2024-05-01T11:30:00Z",
  },
  {
    id: "notification-3",
    userId: "user-4",
    type: "admin",
    entityId: "community-3",
    message: "管理者からのお知らせがあります。",
    isRead: true,
    createdAt: "2024-05-01T12:30:00Z",
  },
  {
    id: "notification-4",
    userId: "user-5",
    type: "like",
    entityId: "post-4",
    message: "田中美咲さんの投稿がいいねされました。",
    isRead: false,
    createdAt: "2024-05-01T13:30:00Z",
  },
  {
    id: "notification-5",
    userId: "user-1",
    type: "comment",
    entityId: "post-5",
    message: "管理者ユーザーの投稿にコメントが付きました。",
    isRead: true,
    createdAt: "2024-05-01T14:30:00Z",
  },
  {
    id: "notification-6",
    userId: "user-2",
    type: "admin",
    entityId: "community-1",
    message: "新しいイベントが追加されました。",
    isRead: false,
    createdAt: "2024-05-01T15:30:00Z",
  },
  {
    id: "notification-7",
    userId: "user-3",
    type: "like",
    entityId: "post-7",
    message: "佐藤花子さんの投稿がいいねされました。",
    isRead: true,
    createdAt: "2024-05-01T16:30:00Z",
  },
  {
    id: "notification-8",
    userId: "user-4",
    type: "comment",
    entityId: "post-8",
    message: "鈴木一郎さんの投稿にコメントが付きました。",
    isRead: false,
    createdAt: "2024-05-01T17:30:00Z",
  },
  {
    id: "notification-9",
    userId: "user-5",
    type: "admin",
    entityId: "community-5",
    message: "カフェ巡り会の新規メンバーが参加しました。",
    isRead: false,
    createdAt: "2024-05-01T18:30:00Z",
  },
  {
    id: "notification-10",
    userId: "user-1",
    type: "like",
    entityId: "post-10",
    message: "管理者ユーザーの投稿がいいねされました。",
    isRead: true,
    createdAt: "2024-05-01T19:30:00Z",
  },
  {
    id: "notification-11",
    userId: "user-2",
    type: "comment",
    entityId: "post-1",
    message: "山田太郎さんの投稿にコメントが付きました。",
    isRead: false,
    createdAt: "2024-05-01T20:30:00Z",
  },
  {
    id: "notification-12",
    userId: "user-3",
    type: "admin",
    entityId: "community-2",
    message: "読書部のイベントが更新されました。",
    isRead: true,
    createdAt: "2024-05-01T21:30:00Z",
  },
  {
    id: "notification-13",
    userId: "user-4",
    type: "like",
    entityId: "post-3",
    message: "鈴木一郎さんの投稿がいいねされました。",
    isRead: false,
    createdAt: "2024-05-01T22:30:00Z",
  },
  {
    id: "notification-14",
    userId: "user-5",
    type: "comment",
    entityId: "post-9",
    message: "田中美咲さんの投稿にコメントが付きました。",
    isRead: true,
    createdAt: "2024-05-01T23:30:00Z",
  },
  {
    id: "notification-15",
    userId: "user-1",
    type: "admin",
    entityId: "community-1",
    message: "管理者からの重要なお知らせ。",
    isRead: false,
    createdAt: "2024-05-02T00:30:00Z",
  },
  {
    id: "notification-16",
    userId: "user-2",
    type: "like",
    entityId: "post-6",
    message: "山田太郎さんの投稿がいいねされました。",
    isRead: true,
    createdAt: "2024-05-02T01:30:00Z",
  },
  {
    id: "notification-17",
    userId: "user-3",
    type: "comment",
    entityId: "post-7",
    message: "佐藤花子さんの投稿にコメントが付きました。",
    isRead: false,
    createdAt: "2024-05-02T02:30:00Z",
  },
  {
    id: "notification-18",
    userId: "user-4",
    type: "admin",
    entityId: "community-4",
    message: "映画サークルの新イベントが追加されました。",
    isRead: false,
    createdAt: "2024-05-02T03:30:00Z",
  },
  {
    id: "notification-19",
    userId: "user-5",
    type: "like",
    entityId: "post-8",
    message: "田中美咲さんの投稿がいいねされました。",
    isRead: true,
    createdAt: "2024-05-02T04:30:00Z",
  },
  {
    id: "notification-20",
    userId: "user-1",
    type: "comment",
    entityId: "post-10",
    message: "管理者ユーザーの投稿にコメントが付きました。",
    isRead: false,
    createdAt: "2024-05-02T05:30:00Z",
  },
];
